<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerURm2xYy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerURm2xYy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerURm2xYy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerURm2xYy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerURm2xYy\App_KernelDevDebugContainer([
    'container.build_hash' => 'URm2xYy',
    'container.build_id' => 'e9ca6273',
    'container.build_time' => 1635244922,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerURm2xYy');
