<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'main' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/main']], [], []],
    'home' => [['id'], ['_controller' => 'App\\Controller\\MainController::home'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/home']], [], []],
    'Mentions-legales' => [[], ['_controller' => 'App\\Controller\\MainController::Mentions_legales'], [], [['text', '/Mentions-legales']], [], []],
    'about' => [[], ['_controller' => 'App\\Controller\\MainController::about'], [], [['text', '/about']], [], []],
    'welcome' => [[], ['_controller' => 'App\\Controller\\MainController::welcome'], [], [['text', '/welcome']], [], []],
    'poker' => [['age'], ['_controller' => 'App\\Controller\\MainController::poker'], [], [['variable', '/', '[^/]++', 'age', true], ['text', '/poker']], [], []],
    'acees' => [['acces'], ['_controller' => 'App\\Controller\\MainController::acces'], [], [['variable', '/', '[^/]++', 'acces', true], ['text', '/acees']], [], []],
    'article' => [['id'], ['_controller' => 'App\\Controller\\MainController::article'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'articles' => [[], ['_controller' => 'App\\Controller\\MainController::articles'], [], [['text', '/articles']], [], []],
    'categorie' => [['id'], ['_controller' => 'App\\Controller\\MainController::categorie'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/categorie']], [], []],
    'categories' => [[], ['_controller' => 'App\\Controller\\MainController::categories'], [], [['text', '/categories']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
